### ISSUE TITLE
After running, nan-labelled duplicated annotation property appears

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/vfb-pipeline-kb2kb#1]
```
MATCH (n {iri:'http://www.geneontology.org/formats/oboInOwl#hasDbXref'}) RETURN n
```
Returns two nodes with same iri.

**Comment by matentzn** [comment]
It appears that this may be due to the fact that dbxrefs are inconsistently represented in the KB:

```
MATCH p=()-[r:hasDbXref {iri:'http://www.geneontology.org/formats/oboInOwl#hasDbXref'}]->() RETURN p LIMIT 10
```

```
MATCH p=()-[r:Annotation {iri:'http://www.geneontology.org/formats/oboInOwl#hasDbXref'}]->() RETURN p LIMIT 10
```

@dosumis , was there any reason for this? The exporter should of course not do what it does, but I was just wondering whether you think dbxrefs should be annotated more consistently.

**Comment by dosumis** [comment]
No, they should be consistent.  Will fix.

**Comment by matentzn** [comment]
Closing this, as core issue is solved. I guess you took a note of the Annotation vs hasDbxref issue @dosumis
